# Generated by Django 5.0.6 on 2024-05-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
